const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const externalCustomerSchema = new Schema({
  ld:                            { type: String, default: "" },
  loanNo:                        { type: String, default: "" },
  branch:                        { type: String, default: "" },
  customerName:                  { type: String, default: "" },
  fatherName:                    { type: String, default: "" },
  mobile:                        { type: [Number], default: [] },
  emailId:                       { type: String, default: "" },
  village:                       { type: String, default: "" },
  address:                       { type: String, default: "" },
  state:                         { type: String, default: "" },
  gender:                        { type: String, default: "" },
  dob:                           { type: String, default: "" },
  age:                           { type: Number, default: 0 },
  cibilScore:                    { type: Number, default: 0 },
  coBorrower1Name:               { type: String, default: "" },
  coBorrower1Mobile:             { type: [Number], default: [] },
  coBorrower1EmailId:            { type: String, default: "" },
  coBorrower1Address:            { type: String, default: "" },
  coBorrower1State:              { type: String, default: "" },
  coBorrower1Gender:             { type: String, default: "" },
  coBorrower1Dob:                { type: String, default: "" },
  coBorrower1Age:                { type: Number, default: 0 },
  coBorrower1CibilScore:         { type: Number, default: 0 },
  gtrName:                       { type: String, default: "" },
  gtrFatherName:                 { type: String, default: "" },
  gtrMobNo:                      { type: [Number], default: [] },
  gtrAddress:                    { type: String, default: "" },
  gtrState:                      { type: String, default: "" },
  gtrGender:                     { type: String, default: "" },
  gtrDob:                        { type: String, default: "" },
  gtrAge:                        { type: Number, default: 0 },
  gtrCibilScore:                 { type: Number, default: 0 },
  guarantorBankName:             { type: String, default: "" },
  bankBranch:                    { type: String, default: "" },
  accountHolderName:             { type: String, default: "" },
  accountNumber:                 { type: String, default: "" },
  ifscCode:                      { type: String, default: "" },
  accountType:                   { type: String, default: "" },
  salesPerson:                   { type: String, default: "" },
  salesManager:                  { type: String, default: "" },
  clusterManager:                { type: String, default: "" },
  pdDoneBy:                      { type: String, default: "" },
  product:                       { type: String, default: "" },
  caseType:                      { type: String, default: "" },
  partnerName:                   { type: String, default: "" },
  loanAmount:                    { type: Number, default: 0 },
  tenure:                        { type: Number, default: 0 },
  roi:                           { type: Number, default: 0 },
  emi:                           { type: Number, default: 0 },
  pfCharges:                     { type: Number, default: 0 },
  documentCharges:               { type: Number, default: 0 },
  cersaiCharges:                 { type: Number, default: 0 },
  insuranceCharges:              { type: Number, default: 0 },
  actualPreEmi:                  { type: Number, default: 0 },
  netDisbursementAmount:         { type: Number, default: 0 },
  sanctionDate:                  { type: String, default: "" },
  disbursementDate:              { type: String, default: "" },
  disbursementMonth:             { type: String, default: "" },
  customerRepaymentBankName:     { type: String, default: "" },
  customerBankBranch:            { type: String, default: "" },
  customerAccountHolderName:     { type: String, default: "" },
  customerAccountNumber:         { type: String, default: "" },
  customerIfscCode:              { type: String, default: "" },
  customerAccountType:           { type: String, default: "" },
  nachDoneBy:                    { type: String, default: "" },
  nachTokenId:                   { type: String, default: "" },
  propertyPaperType:             { type: String, default: "" },
  propertyType:                  { type: String, default: "" },
  marketValue:                   { type: Number, default: 0 },
  ltv:                           { type: Number, default: 0 },
  lat:                           { type: String, default: "" },
  long:                          { type: String, default: "" },
  monthlyIncome:                 { type: Number, default: 0 },
  monthlyObligations:            { type: Number, default: 0 },
  foir:                          { type: Number, default: 0 },
  customerProfile:               { type: String, default: "" },
  customerSegment:               { type: String, default: "" },
  allocatedBranch:               { type: String, default: "" },
  allocation1:                   { type: String, default: "" },
  allocation2:                   { type: String, default: "" },
  allocation3:                   { type: String, default: "" },
  allocation4:                   { type: String, default: "" },
  allocation5:                   { type: String, default: "" },
  emiCycle:                      { type: String, default: "" },
  firstEmiDate:                  { type: String, default: "" },
  firstEmiMonth:                 { type: String, default: "" },
  lastEmiDate:                   { type: String, default: "" },
  collectionType:                { type: String, default: "" },
  lastEmiReceivedDate:           { type: String, default: "" },
  netDue:                        { type: Number, default: 0 },
  oldDue:                        { type: Number, default: 0 },
  posOutstanding:                { type: Number, default: 0 },
  interestOutstanding:           { type: Number, default: 0 }
}, {
  timestamps: true
});

const ExternalCustomerModel = mongoose.model("googledata", externalCustomerSchema);

module.exports = ExternalCustomerModel;
