const mongoose = require('mongoose');
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;

const fileProcessModel = new Schema({
    LD:                   { type: String , default :"" },
    customerName:         { type: String , default :"" },
    employeeId1:          { type: ObjectId, default:null },
    applicantkyc:         { type: String , default :"" },
    applicantDate:        { type: String , default :"" },
    coApplicantKyc:       { type: String , default :"" },
    coApplicantDate:      { type: String , default :"" },
    gaurantorKyc:         { type: String , default :"" },
    gaurantorDate:        { type: String , default :"" },
    electricityBill:      { type: String , default :"" },
    elctricityDate:       { type: String , default :"" },
    samagraId:            { type: String , default :"" },
    samagraDate:          { type: String , default :"" },
    udyamCertificate:     { type: String , default :"" },
    udyamCertificateDate: { type: String , default :"" },
    bankStatement:        { type: String , default :"" },
    bankStatementDate:    { type: String , default :"" }, 
    incomeDocument:       { type: String , default :"" },
    incomeDate:           { type: String , default :"" },
    propertyPapers:       { type: String , default :"" },
    propertyPapersDate:   { type: String , default :"" },
    applicantPdc:         { type: String , default :"" },
    applicantPdcDate:     { type: String , default :"" },
    gurantorPdc:          { type: String , default :"" },
    gurantorPdcDate:      { type: String , default :"" },
    esignPhoto:           { type: String , default :"" },
    esignPhotosDate:      { type: String , default :"" },
    nachRegistration:     { type: String , default :"" },
    nachRegistrationDate: { type: String , default :"" },
    physicalFileCourier:  { type: String , default :"" },
    physicalFileDate:     { type: String , default :"" },
    enachLink:            { type: String , default :"" },
    enachLinkDate:        { type: String , default :"" },
    appEsignLink:         { type: String , default :"" },
    appEsignDate:         { type: String , default :"" },
    coAppEsignLink:       { type: String , default :"" },
    coAppEsignDate:       { type: String , default :"" },
    gtrEsignLink:         { type: String , default :"" },
    gtrEsignDate:         { type: String , default :"" },
    additional1:          { type: String , default :"" },
    additionalDate1:      { type: String , default :"" },
    additional2:          { type: String , default :"" },
    additionalDate2:      { type: String , default :"" },
    additional3:          { type: String , default :"" },
    additionalDate3:      { type: String , default :"" },
    additional4:          { type: String , default :"" },
    additionalDate4:      { type: String , default :"" },
    employeeId2:          { type: ObjectId, default:null },
    googleForm:           { type: String , default :"" },
    googleFormDate:       { type: String , default :"" },
    appCibilReport:       { type: String , default :"" },
    appCibilReportDate:   { type: String , default :"" },
    coAppCibilReport:     { type: String , default :"" },
    coAppCibilReportDate: { type: String , default :"" },
    gtrCibilReport:       { type: String , default :"" },
    gtrCibilReportDate:   { type: String , default :"" },
    pdReportKyc:          { type: String , default :"" },
    pdReportDate:         { type: String , default :"" },
    camReport:            { type: String , default :"" },
    camDate:              { type: String , default :"" },
    tvr:                  { type: String , default :"" },
    tvrDate:              { type: String , default :"" },
    legal:                { type: String , default :"" },
    legalDate:            { type: String , default :"" },
    technical:            { type: String , default :"" },
    technicalDate:        { type: String , default :"" },
    fc:                   { type: String , default :"" },
    fcDate:               { type: String , default :"" },
    soa:                  { type: String , default :"" },
    soaDate:              { type: String , default :"" },
    lod:                  { type: String , default :"" },
    lodDate:              { type: String , default :"" },
    sentForSanction:      { type: String , default :"" },
    sanctionDate:         { type: String , default :"" },
    sanctionFromPartner :   { type: String , default :"" },
    sanctionFromPartnerDate:{ type: String , default :"" },
    employeeId3:          { type: ObjectId, default:null },
    rmPayment:            { type: String , deafault :"" },
    rmPaymentDate:        { type: String , default :"" },
    rmBooked:             { type: String , deafault :"" },
    rmBookedDate:         { type: String , default :"" },
    rmReceived:           { type: String , deafault :"" },
    rmReceivedDate:       { type: String , default :"" },
    employeeId4:          { type: ObjectId, default:null },
    rcuReport:            { type: String , default :"" },
    rcuDate:              { type: String , default :"" },
    esign:                { type: String , default :"" },
    esignDate:            { type: String , default :"" },
    otherDisbursement:    { type: String , default :"" },
    otherDisbursementDate:{ type: String , default :"" },
    sentForDisbursement:  { type: String , default :"" },
    disbursementDate:     { type: String , default :"" },
    disbursementUTR:      { type: String , default :"" },
    disbursementUTRDate:  { type: String , default :"" },
    jainumEntry:          { type: String , default :"" },
    jainumEntryDate:      { type: String , default :"" },
    misUpdation:          { type: String , default :"" },
    misUpdationDate:      { type: String , default :"" },
    employeeId5:          { type: ObjectId, default:null },
    propertyPaperPartner:      { type: String , deafault :"" },
    propertyPaperPartnerDate:  { type: String , default :"" },
    nocPartner:                { type: String , deafault :"" },
    nocPartnerDate:            { type: String , default :"" },
    fileInventory:             { type: String , deafault :"" },
    fileInventoryDate:         { type: String , default :"" },
    chequeInventory:           { type: String , deafault :"" },
    chequeInventoryDate:       { type: String , default :"" },
    loanNo:                    { type: String , deafault :"" },
    loanNoDate:                { type: String , default :"" },
    status:               { type: String, enum: ['active', 'inactive'], default: 'active' },

},
{
    timestamps: true,
  }
);

const fileProcessDetail = mongoose.model('fileProcess', fileProcessModel);

module.exports = fileProcessDetail;
