const mongoose = require("mongoose");
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;

const LMSSchema = new Schema({
  aadharNo: { type: String, default: "" },
  accountMode: { type: String, default: "" },
  annualIncome: { type: String, default: "" },
  areaName: { type: String, default: "" },
  birthDate: { type: String, default: "" },
  caste: { type: String, default: "" },
  cityCode: { type: String, default: "" },
  cityName: { type: String, default: "" },
  countryName: { type: String, default: "" },
  customerId: { type: String, default: "" },
  customerType: { type: String, default: "" },
  districtName: { type: String, default: "" },
  drivingLicNo: { type: String, default: "" },
  education: { type: String, default: "" },
  electionIdNo: { type: String, default: "" },
  emailId: { type: String, default: "" },
  employment: { type: String, default: "" },
  externalRefNo: { type: String, default: "" },
  fatherFirstName: { type: String, default: "" },
  fatherLastName: { type: String, default: "" },
  fatherMiddleName: { type: String, default: "" },
  fatherOrSpouse: { type: String, default: "" },
  fatherPrefix: { type: String, default: "" },
  firstName: { type: String, default: "" },
  gender: { type: String, default: "" },
  inceptionDate: { type: String, default: "" },
  jointHolder: [
    {
      aadharNo: { type: String, default: "" },
      annualIncome: { type: String, default: "" },
      areaName: { type: String, default: "" },
      birthDate: { type: String, default: "" }, // Consider changing to Date type if needed
      caste: { type: String, default: "" },
      cbsCategCode: { type: String, default: "" },
      cityCode: { type: String, default: "" },
      cityName: { type: String, default: "" },
      countryName: { type: String, default: "" },
      customerId: { type: String, default: "" },
      districtName: { type: String, default: "" },
      drivingLicNo: { type: String, default: "" },
      education: { type: String, default: "" },
      electionIdNo: { type: String, default: "" },
      emailId: { type: String, default: "" },
      employment: { type: String, default: "" },
      fatherFirstName: { type: String, default: "" },
      fatherLastName: { type: String, default: "" },
      fatherMiddleName: { type: String, default: "" },
      fatherOrSpouse: { type: String, default: "" },
      fatherPrefix: { type: String, default: "" },
      firstName: { type: String, default: "" },
      gender: { type: String, default: "" },
      inceptionDate: { type: String, default: "" }, // Consider changing to Date type if needed
      lastName: { type: String, default: "" },
      maritalStatus: { type: String, default: "" },
      middleName: { type: String, default: "" },
      mobileNo: { type: String, default: "" },
      motherFirstName: { type: String, default: "" },
      motherLastName: { type: String, default: "" },
      motherMiddleName: { type: String, default: "" },
      motherPrefix: { type: String, default: "" },
      occupation: { type: String, default: "" },
      pan: { type: String, default: "" },
      permanentAddress1: { type: String, default: "" },
      permanentAddress2: { type: String, default: "" },
      permanentAddress3: { type: String, default: "" },
      pincode: { type: String, default: "" },
      placeOfIncorporation: { type: String, default: "" },
      prefix: { type: String, default: "" },
      proofOfAddress: { type: String, default: "" },
      referenceNumber: { type: String, default: "" },
      relatedPersonType: { type: String, default: "" },
      religion: { type: String, default: "" },
      residenceStatus: { type: String, default: "" },
      stateName: { type: String, default: "" },
      type: { type: String, default: "" },
    },
  ],

  lastName: { type: String, default: "" },
  loanApplicationDate: { type: String, default: "" },
  loanAppliedAmount: { type: Number, default: 0 },
  loanInstallmentType: { type: String, default: "" },
  loanPurpose: { type: String, default: "" },
  makerUser: { type: String, default: "" },
  maritalStatus: { type: String, default: "" },
  middleName: { type: String, default: "" },
  mobileNo: { type: Number},
  motherFirstName: { type: String, default: "" },
  motherLastName: { type: String, default: "" },
  motherMiddleName: { type: String, default: "" },
  motherPrefix: { type: String, default: "" },
  noofInstallment: { type: Number, default: 0 },
  occupation: { type: String, default: "" },
  pan: { type: String, default: "" },
  permanentAddress1: { type: String, default: "" },
  permanentAddress2: { type: String, default: "" },
  permanentAddress3: { type: String, default: "" },
  pincode: { type: Number, default: 0 },
  placeOfIncorporation: { type: String, default: "" },
  prefix: { type: String, default: "" },
  proofOfAddress: { type: String, default: "" },
  referenceNumber: { type: String, default: "" },
  religion: { type: String, default: "" },
  reqBranchCd: { type: String, default: "" },
  reqCallerNm: { type: String, default: "" },
  reqProductCode: { type: String, default: "" },
  residenceStatus: { type: String, default: "" },
  roi: { type: Number, default: 0 },
  stateName: { type: String, default: "" },
  typeOfAccount: { type: String, default: "" },
  riskCateg: { type: String, default: "" },
  relatedPersonType: { type: String, default: "" },
},
{
  timestamps: true,
}
);


const LMSSchemaModel = mongoose.model("ratnaaFin", LMSSchema);

module.exports = LMSSchemaModel