const mongoose = require('mongoose');
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;

const cibilScoreReportKycSchema = new Schema({
  customerId: { type: Schema.Types.ObjectId, ref: "customerdetail" },

        employeeId:              { type: ObjectId , default :null },
        LD:                      { type: String , default :"" },
        customerName:            { type: String , default :"" },
        applicantCibilScore:     { type: Number , default: null },
        totalAccounts:            { type: Number , default: null },
        overdueAccount:           { type: Number , default: null },
        zeroBalanceAccount:       { type: Number , default: null },
        highCreditSanctionAmount:{ type: Number , default: 0  },
        totalCurrentOutstanding:  { type: Number , default: null },
        totalOverdueAmount:      { type: Number , default: null },
        totalNumberOfEnquiry:     { type: Number , default: null },
        existingLoanRunningLoanType1:        { type: String, default: "" },
        existingLoanRunningOwnership1:       { type: String, default: "" },
        existingLoanRunningSanctionedAmount1:{ type: Number , default: null },
        existingLoanRunningCurrentBalance1:  { type: Number , default: null },
        existingLoanRunningRoi1:             { type: Number , default: null },
        existingLoanRunningEmi1:             { type: Number , default: null },
        existingLoanRunningTotalTenure1:     { type: Number , default: null },
        existingLoanRunningBalanceTenure1:   { type: Number , default: null },
        existingLoanRunningLoanStatus1:      { type: String, default: "" },
        existingLoanRunningLoanObligated1:   { type: String, default: "" },
        existingLoanRunningObligationConsideredAmount1:  { type: Number , default: null },
        existingLoanRunningLoanType2:                   { type: String, default: "" },
        existingLoanRunningOwnership2:                  { type: String, default: "" },
        existingLoanRunningSanctionedAmount2:           { type: Number , default: null },
        existingLoanRunningCurrentBalance2:             { type: Number , default: null },
        existingLoanRunningRoi2:                        { type: Number , default: null },
        existingLoanRunningEmi2:                        { type: Number , default: null },
        existingLoanRunningTotalTenure2:                { type: Number , default: null },
        existingLoanRunningBalanceTenure2:              { type: Number , default: null },
        existingLoanRunningLoanStatus2:                 { type: String, default: "" },
        existingLoanRunningLoanObligated2:              { type: String, default: "" },
        existingLoanRunningObligationConsideredAmount2: { type: Number , default: null },
        coAppName:                                      { type: String, default: "" },
        coAppCibilScore:                                { type: Number , default: null },
        coAppTotalAccounts:                             { type: Number , default: null },
        coAppOverdueAccount:                            { type: Number , default: null },
        coAppZeroBalanceAccount:                        { type: Number , default: null },
        coAppHighCreditSanctionAmount:                  { type: Number , default: null },
        coAppTotalCurrentOutstanding:                    { type: Number , default: null },
        coAppTotalOverdueAmount:                        { type: Number , default: null },
        coAppExistingLoanRunningLoanType1:              { type: String, default: "" },
        coAppExistingLoanRunningOwnership1:             { type: String, default: "" },
        coAppExistingLoanRunningSanctionedAmount1:      { type: Number , default: null },
        coAppExistingLoanRunningCurrentBalance1:        { type: Number , default: null },
        coAppExistingLoanRunningRoi1:                   { type: Number , default: null },
        coAppExistingLoanRunningEmi1:                   { type: Number , default: null },
        coAppExistingLoanRunningTotalTenure1:           { type: Number , default: null },
        coAppExistingLoanRunningBalanceTenure1:         { type: Number , default: null },
        coAppExistingLoanRunningLoanStatus1:            { type: String, default: "" },
        coAppExistingLoanRunningLoanObligated1:         { type: String, default: "" },
        coAppExistingLoanRunningObligationConsideredAmount1: { type: String, default: "" },
        coAppExistingLoanRunningLoanType2:                   { type: String, default: "" },
        coAppExistingLoanRunningOwnership2:                  { type: String, default: "" },
        coAppExistingLoanRunningSanctionedAmount2:           { type: Number , default: null },
        coAppExistingLoanRunningCurrentBalance2:             { type: Number , default: null },
        coAppExistingLoanRunningRoi2:                        { type: Number , default: null },
        coAppExistingLoanRunningEmi2:                        { type: Number , default: null },
        coAppExistingLoanRunningTotalTenure2:                { type: Number , default: null },
        coAppExistingLoanRunningBalanceTenure2:              { type: Number , default: null },
        coAppExistingLoanRunningLoanStatus2:                 { type: String, default: "" },
        coAppExistingLoanRunningLoanObligated2:              { type: String, default: "" },
        coAppExistingLoanRunningObligationConsideredAmount2: { type: Number , default: null },
        gtrName:       { type: String, default: "" },
        gtrCibilScore: { type: Number, default: null }   
},
{
    timestamps: true,
  }
);

const cibilReportKycModel = mongoose.model('cibilReportKyc', cibilScoreReportKycSchema);

module.exports = cibilReportKycModel;
