const mongoose = require('mongoose');
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;

const pdReportKycSchema = new Schema({
        employeeId:    { type: ObjectId , default :null },
        LD:            { type: String , default :"" },
        customerName:  { type: String , default :"" },
        branchName: { type: String, default: "" },
        customerFatherName: { type: String, default: "" },
        customerMotherName: { type: String, default: "" },
        customerSpouseWifeName: { type: String, default: "" },
        customerDob: { type: String, default: "" },
        customerHigherEducation: { type: String, default: "" },
        customerMobileNumber: { type: String, default: "" },
        customerMarriageStatus: { type: String, default: "" },
        numberOfDependantOnCustomers: { type: String, default: "" },
        customerPhoto: { type: String, default: "" },
        customerKycPhoto: { type: String, default: "" },
        coApplicantName: { type: String, default: "" },
        coApplicantFatherName: { type: String, default: "" },
        coApplicantMotherName: { type: String, default: "" },
        coApplicantSpouseWifeName: { type: String, default: "" },
        coApplicantRelationWithApplicant: { type: String, default: "" },
        coApplicantDob: { type: String, default: "" },
        coApplicantType: { type: String, default: "" },
        coApplicantHigherEducation: { type: String, default: "" },
        coApplicantMobileNumber: { type: String, default: "" },
        coApplicantMarriageStatus: { type: String, default: "" },
        coApplicantPhoto: { type: String, default: "" },
        additionalCoApplicantDetails: { type: String, default: "" },
        coApplicant2Name: { type: String, default: "" },
        coApplicant2FatherName: { type: String, default: "" },
        coApplicant2MotherName: { type: String, default: "" },
        coApplicant2SpouseWifeName: { type: String, default: "" },
        coApplicant2RelationWithApplicant: { type: String, default: "" },
        coApplicant2Dob: { type: String, default: "" },
        coApplicant2Type: { type: String, default: "" },
        coApplicant2HigherEducation: { type: String, default: "" },
        coApplicant2MobileNumber: { type: String, default: "" },
        addressAsPerAadharCopy: { type: String, default: "" },
        coApplicant2MarriageStatus: { type: String, default: "" },
        coApplicant2PanNumber: { type: String, default: "" },
        coApplicant2AadharNumber: { type: String, default: "" },
        coApplicant2DrivingLicenceNumber: { type: String, default: "" },
        coApplicant2VoterIdNumber: { type: String, default: "" },
        coApplicant2Photo: { type: String, default: "" },
        coApplicant2KycPhoto: { type: String, default: "" },
        guarantorDetails: { type: String, default: "" },
        guarantorName: { type: String, default: "" },
        guarantorFatherName: { type: String, default: "" },
        guarantorMotherName: { type: String, default: "" },
        guarantorSpouseWifeName: { type: String, default: "" },
        guarantorRelationWithApplicant: { type: String, default: "" },
        guarantorType: { type: String, default: "" },
        guarantorDob: { type: String, default: "" },
        guarantorHigherEducation: { type: String, default: "" },
        guarantorMobileNumber: { type: String, default: "" },
        guarantorMarriageStatus: { type: String, default: "" },
        guarantorPanNumber: { type: String, default: "" },
        guarantorAadharNumber: { type: String, default: "" },
        guarantorVoterIdNumber: { type: String, default: "" },
        guarantorDrivingLicenceNumber: { type: String, default: "" },
        guarantorPhoto: { type: String, default: "" },
        guarantorKycPhoto: { type: String, default: "" },
        agriLandDetails: { type: String, default: "" },
        nameOfAgriOwner: { type: String, default: "" },
        agriOwnerRelationWithApplicant: { type: String, default: "" },
        agriLandInBigha: { type: String, default: "" },
        agriLandSurveyKhasraNumber: { type: String, default: "" },
        villageName: { type: String, default: "" },
        whichCropIsPlanted: { type: String, default: "" },
        howMuchSoldForLastCrop: { type: String, default: "" },
        fertilizerShopOwnerName: { type: String, default: "" },
        fertilizerShopOwnerContactNumber: { type: String, default: "" },
        agriLandPavati: { type: String, default: "" },
        incomeFromDairyBusiness: { type: String, default: "" },
        numberOfCattleAvailable: { type: String, default: "" },
        numberOfMilkGivingCattles: { type: String, default: "" },
        totalMilkSupplyPerDay: { type: String, default: "" },
        nameOfDairyOwner: { type: String, default: "" },
        mobileNumberOfDairyOwner: { type: String, default: "" },
        milkSupplyingFromSinceYear: { type: String, default: "" },
        monthlyExpensesOnMilkBusiness: { type: String, default: "" },
        monthlyIncomeFromMilkBusiness: { type: String, default: "" },
        milkBookDiaryPhoto: { type: String, default: "" },
        cattlePhoto: { type: String, default: "" },
        otherSourceOfIncome: { type: String, default: "" },
        businessName: { type: String, default: "" },
        businessOwnerName: { type: String, default: "" },
        relationWithApplicant: { type: String, default: "" },
        natureOfBusiness: { type: String, default: "" },
        businessBoardSeen: { type: String, default: "" },
        businessDoingFromYears: { type: String, default: "" },
        businessMonthlyIncome: { type: String, default: "" },
        shopPhotoAlongWithCustomer: { type: String, default: "" },
        salaryIncome: { type: String, default: "" },
        salaryEarningMemberName: { type: String, default: "" },
        salaryRelationWithApplicant: { type: String, default: "" },
        salaryIncomeFrom: { type: String, default: "" },
        addressOfSalaryProvider: { type: String, default: "" },
        mobileNumberOfSalaryProvider: { type: String, default: "" },
        doingFromYears: { type: String, default: "" },
        salaryPaidThrough: { type: String, default: "" },
        monthlySalary: { type: String, default: "" },
        salaryCertificateDeclarationLetter: { type: String, default: "" },
        propertyDetails: { type: String, default: "" },
        nameOfPropertyOwner: { type: String, default: "" },
        relationWithApplicantProperty: { type: String, default: "" },
        residenceType: { type: String, default: "" },
        areaOfConstructionInSqFt: { type: String, default: "" },
        houseConstructionStatus: { type: String, default: "" },
        numberOfRooms: { type: String, default: "" },
        completeConstructionDetails: { type: String, default: "" },
        eastBoundary: { type: String, default: "" },
        westBoundary: { type: String, default: "" },
        northBoundary: { type: String, default: "" },
        southBoundary: { type: String, default: "" },
        pattaAvailableWithCustomer: { type: String, default: "" },
        boundariesMatchingWithPattaDocs: { type: String, default: "" },
        ageOfHouse: { type: String, default: "" },
        landmark: { type: String, default: "" },
        assetsSeenAtResidence: { type: String, default: "" },
        propertyDocsPhoto: { type: String, default: "" },
        overallHousePhoto: { type: String, default: "" },
        housePhotoWithCustomer: { type: String, default: "" },
        existingLoanDetails: { type: String, default: "" },
        loanType: { type: String, default: "" },
        existingMonthlyEmi: { type: String, default: "" },
        existingOutstandingLoan: { type: String, default: "" },
        loanType2: { type: String, default: "" },
        existingMonthlyEmi2: { type: String, default: "" },
        existingOutstandingLoan2: { type: String, default: "" },
        loanRequirementDetails: { type: String, default: "" },
        loanAmountDemandByCustomer: { type: String, default: "" },
        endUseOfLoan: { type: String, default: "" },
        cattleToBePurchased: { type: String, default: "" },
        emiComfortAmount: { type: String, default: "" },
        expectedLoanTenureInMonths: { type: String, default: "" },
        referenceDetails: { type: String, default: "" },
        neighbourName1: { type: String, default: "" },
        neighbourRelationWithApplicant1: { type: String, default: "" },
        neighbourAddress1: { type: String, default: "" },
        neighbourMobileNumber1: { type: String, default: "" },
        neighbourName2: { type: String, default: "" },
        neighbourRelationWithApplicant2: { type: String, default: "" },
        neighbourAddress2: { type: String, default: "" },
        neighbourMobileNumber2: { type: String, default: "" },
        overallNeighbourFeedback: { type: String, default: "" },
        geoPhotoWithOtherSource: { type: String, default: "" },
        netMonthlyIncome: { type: String, default: "" },
        estimatedEligibleLoanAmount: { type: String, default: "" },
        finalDecision: { type: String, default: "" },
        finalRemarks: { type: String, default: "" },
        hoCreditDesk: { type: String, default: "" }
      
},
{
    timestamps: true,
  }
);

const pdReportKycModel = mongoose.model('pdReportKyc', pdReportKycSchema);

module.exports = pdReportKycModel;
