const mongoose = require('mongoose');
const Schema = mongoose.Schema;
ObjectId = Schema.ObjectId;

const samagraIdModel = new Schema({
    employeeId:                       { type: ObjectId , default :null },
    LD:                               { type: String , default :"" },
    customerName:                     { type: String , default :"" },
    samagraFamilyId:                  { type: String , default :"" },
    samagraFamilyHeadName:              { type: String , default :"" },
    samagraMemberId1:                 { type: String , default :"" },
    samagraMemberName1:             { type: String , default :"" },
    samagraMemberAge1:              { type: Number , default :null },
    samagraMemberGender1:           { type: String , default :"" },
    memberRelationWithApplicant1:     { type: String , default :"" },
    samagraMemberId2:                 { type: String , default :"" },
    samagraMemberName2:             { type: String , default :"" },
    samagraMemberAge2:               { type: Number , default :null },
    samagraMemberGender2:           { type: String , default :"" },
    memberRelationWithApplicant2:     { type: String , default :"" },
    samagraMemberId3:                 { type: String , default :"" },
    samagraMemberName3:             { type: String , default :"" },
    samagraMemberAge3:               { type: Number , default :null },
    samagraMemberGender3:           { type: String , default :"" },
    memberRelationWithApplicant3:     { type: String , default :"" },
    samagraMemberId4:                 { type: String , default :"" },
    samagraMemberName4:             { type: String , default :"" },
    samagraMemberAge4:               { type: Number , default :null },
    samagraMemberGender4:           { type: String , default :"" },
    memberRelationWithApplicant4:     { type: String , default :"" },
    samagraMemberId5:                 { type: String , default :"" },
    samagraMemberName5:             { type: String , default :"" },
    samagraMemberAge5:               { type: Number , default :null },
    samagraMemberGender5:           { type: String , default :"" },
    memberRelationWithApplicant5:     { type: String , default :"" },
    samagraMemberId6:                 { type: String , default :"" },
    samagraMemberName6:             { type: String , default :"" },
    samagraMemberAge6:               { type: Number , default :null },
    samagraMemberGender6:           { type: String , default :"" },
    memberRelationWithApplicant6:     { type: String , default :"" },
    samagraMemberId7:                 { type: String , default :"" },
    samagraMemberName7:             { type: String , default :"" },
    samagraMemberAge7:              { type: Number , default :null },
    samagraMemberGender7:           { type: String , default :"" },
    memberRelationWithApplicant7:     { type: String , default :"" },
    samagraMemberId8:                 { type: String , default :"" },
    samagraMemberName8:             { type: String , default :"" },
    samagraMemberAge8:               { type: Number , default :null },
    samagraMemberGender8:           { type: String , default :"" },
    memberRelationWithApplicant8:     { type: String , default :"" },
    samagraMemberId9:                 { type: String , default :"" },
    samagraMemberName9:             { type: String , default :"" },
    samagraMemberAge9:               { type: Number , default :null },
    samagraMemberGender9:           { type: String , default :"" },
    memberRelationWithApplicant9:     { type: String , default :"" },
    samagraMemberId10:                { type: String , default :"" },
    samagraMemberName10:            { type: String , default :"" },
    samagraMemberAge10:              { type: Number , default :null },
    samagraMemberGender10:          { type: String , default :"" },
    memberRelationWithApplicant10:    { type: String , default :"" },
},
{
    timestamps: true,
  }
);

const samagraIdDetail = mongoose.model('samagraIdKyc', samagraIdModel);

module.exports = samagraIdDetail;
