const express = require("express");
const router = express.Router();

const countryDetail = require("./country.routes")
const permissionFormRouter = require("./permissionForm.routes")
const accessRightsRouter = require("./accessRight.routes")
const companyRouter = require("./company.routes")
const branchRouter = require("./branch.routes")
const incomeTypeRouter = require("./incomeType.routes");
const roleDetail = require("./role.routes");
const productDetail = require("./product.routes")
const departmentDetail = require("./department.routes")
const designationDetail = require("./designation.routes")
const workLocationDetail = require("./workLocation.routes")
const employeDetail = require("./empolye.routes")
const employmentTypeDetail = require("./employmentType.routes")
const employeTypeDetail = require("./employeType.routes")
const costCenterDetail = require("./costCenter.routes")
const customerResponse = require('./customerResponse.routes')
const modeOfCollection = require('./modeOfCollection.routes')
const okCreditDetail = require('./okCredit.routes')
const vendorType = require('./vendorType.routes')
const vendorDetail = require('./vendor.routes')
const pdfTemplateDetail = require('./pdfTemplate.router')
const bankNameDetail = require('./bank.routes')
const transferBankNameDetail = require('./transferBankName.routes')
const dropdownDetail = require('./dropdown.routes')
const noticeType = require('./noticeType.routes')
const legalNoticeDetail = require('./legalNotice.routes')
const departmentRouter = require('./newDepartment.routes')
const employeeAllocation = require('./employeeAllocation.routes')
const emiCallingAllocation = require('./emiCallingAllocation.routes')
const scrollingTextDetail = require('./scrollingText.route')
const customerLMSDetail = require('./customerLms.routes')
const targetForm = require('./targetForm.routes')
const finalDropdownDetail = require('./finalDropdown.routes')
const trackerDropdown = require('./trackerDropdown.routes')
const tvrFormQuestionDetail = require('./tvrFormQuestion.routes')
const loanTypeDetail = require('./loanType.routes')
const incomeCatagoryDetail = require('./incomeCatagory.routes')
const propertyTypeDetail = require('./propertyType.routes')
const newDetail = require("./news.routes")
const activeLoanType = require("./customerActiveLoanType.router")
const notesDetail = require("./notes.routes")

router.use("/country",          countryDetail)
router.use("/permissionForm",   permissionFormRouter)
router.use("/accessRights",    accessRightsRouter)
router.use("/company",          companyRouter)
router.use("/branch",           branchRouter)
router.use("/incomeType",       incomeTypeRouter);
router.use("/role",             roleDetail)
router.use("/product",          productDetail)
router.use("/newdepartment",    departmentRouter)
router.use("/department",       departmentDetail)
router.use("/designation",      designationDetail)
router.use("/workLocation",     workLocationDetail)
router.use("/employe",          employeDetail)
router.use("/employmentType",   employmentTypeDetail)
router.use("/employeType",      employeTypeDetail)
router.use("/costCenter",       costCenterDetail)
router.use("/customerResponse", customerResponse)
router.use("/modeOfCollection", modeOfCollection)
router.use("/okCredit",         okCreditDetail)
router.use("/vendorType",       vendorType)
router.use("/vendor",           vendorDetail)
router.use("/pdfTemplate",      pdfTemplateDetail)
router.use("/bankName",         bankNameDetail)
router.use("/transferBankName", transferBankNameDetail)
router.use("/dropdown",         dropdownDetail)
router.use("/noticeType",       noticeType)
router.use("/legalNotice",      legalNoticeDetail)
router.use("/allocation", employeeAllocation)
router.use("/emiCallingAllocation",emiCallingAllocation)
router.use("/scrollingText",scrollingTextDetail)
router.use("/customerLMS", customerLMSDetail)
router.use("/target", targetForm)
router.use("/titleForm",finalDropdownDetail)
router.use("/trackerDropdown",trackerDropdown)
router.use("/tvrFormQuestion",tvrFormQuestionDetail)
router.use("/loanType",loanTypeDetail)
router.use("/incomeCatagory",incomeCatagoryDetail)
router.use("/propertyType",propertyTypeDetail)
router.use("/newDetail",newDetail)
router.use("/activeLoanType",activeLoanType)
router.use("/notes",notesDetail)

module.exports = router;
